site_name: Spokane Python User Group
site_url: https://spokanepython.com/
site_description: Home of the Spokane Python User Group 🐍
repo_url: https://github.com/Intellitect-Samples/SpokanePythonUserGroup
repo_name: SpokanePythonUserGroup

theme:
  name: material
  custom_dir: overrides
  logo: img/favicon.svg
  favicon: img/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.expand
    - navigation.sections
  plugins:
    - search
    - social
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/termynal.css

extra_javascript:
  - scripts/termynal.js

markdown_extensions:
  - attr_list
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - "Spokane Python User Group": "index.md"
  - "About SPUG": "about.md"
  - "Getting Started with Python": "getting-started.md"
  - "Meetups":
      - "Pragmatic Python V: All Things Hosting": "meetups/all-things-hosting.md"
      - "Pragmatic Python IV: Adventures in A.I.": "meetups/adventures-in-ai.md"
      - "Pragmatic Python III: An Anything but Mundane Intro to Machine Learning": "meetups/intro-to-machine-learning.md"
      - "Pragmatic Python II: Journey to the Pythonic Peak": "meetups/pragmatic-python-02.md"
      - "Pragmatic Python I: Welcome to the Jungle": "meetups/pragmatic-python-01.md"
      - "Mk’ing spokanepython.com": "meetups/static-site-generation.md"
      - "Background Task Processing": "meetups/background-task-processing.md"
      - "Kubernetes and Python": "meetups/kubernetes.md"
      - "Typing for Fun and Profit": "meetups/typing-for-fun-and-profit.md"
      - "Getting Started with FastAPI": "meetups/getting-started-with-fastapi.md"

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pythonspokane
    - icon: fontawesome/brands/github
      link: https://github.com/python-spokane/
