site_name: Spokane Python User Group
site_url: https://spokanepython.com/
repo_url: https://github.com/Intellitect-Samples/SpokanePythonUserGroup
theme:
  name: material
  logo: img/favicon.png
  favicon: img/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.expand
  plugins:
    - search
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
nav:
  - Home: "index.md"
  - "Meetups":
      - "7/21 - Background Task Processing": "2021-07-Background-Task-Processing.md"
      - "7/21 - Kubernetes": "2021-07-Kubernetes.md"
      - "6/21 - Typing for Fun and Profit": "2021-06-Typing-for-Fun-and-Profit.md"
      - "5/21 - Getting Started with FastAPI": "2021-05-Getting-Started-with-FastAPI.md"
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
