site_name: Spokane Python User Group
site_url: https://spokanepython.com/
repo_url: https://github.com/Intellitect-Samples/SpokanePythonUserGroup
repo_name: SpokanePythonUserGroup

theme:
  name: material
  logo: img/favicon.png
  favicon: img/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.expand
    - navigation.sections
  plugins:
    - search
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: "index.md"
  - "Meetups":
      - "Mk’ing spokanepython.com": "2021.08.24-Static-Site-Generation-with-MkDocs.md"
      - "Background Task Processing": "2021-07-Background-Task-Processing.md"
      - "Kubernetes": "2021-07-Kubernetes.md"
      - "Typing for Fun and Profit": "2021-06-Typing-for-Fun-and-Profit.md"
      - "Getting Started with FastAPI": "2021-05-Getting-Started-with-FastAPI.md"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/joeriddles/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joseph-riddle/
